//
//  Visa.m
//  Visa Checker
//
//  Created by apple on 15/11/2017.
//  Copyright © 2017 Nixon Pang. All rights reserved.
//

#import "Visa.h"

@implementation Visa

-(id)init
{
    self = [super init];
    if (self) {
        /*
        self.pickerArray = [NSArray arrayWithObjects:
                            
                            // A
                            @[@"Afghanistan"],
                            @[@"Albania"],
                            @[@"Algeria"],
                            @[@"Andorra"],
                            @[@"Angola"],
                            @[@"Anguillia"],
                            @[@"Antigua & Barbuda"],
                            @[@"Argentina"],
                            @[@"Armenia"],
                            @[@"Australia"],
                            @[@"Austria"],
                            @[@"Azerbaijan"],
                            // B
                            @[@"Bahamas"],
                            @[@"Bahrain"],
                            @[@"Bangladesh"],
                            @[@"Barbados"],
                            @[@"Belarus"],
                            @[@"Belize"],
                            @[@"Benin"],
                            @[@"Bermuda"],
                            @[@"Bhutan"],
                            @[@"Bolivia"],
                            @[@"Bosnia & Herzegovina"],
                            @[@"Botzwana"],
                            @[@"Brazil"],
                            @[@"Brunei"],
                            @[@"Bulgaria"],
                            @[@"Burkina Faso"],
                            @[@"Burma / Myanmar"],
                            @[@"Burundi"],
                            // C
                            @[@"Cambodia"],
                            @[@"Cameroon"],
                            @[@"Canada"],
                            @[@"Cape Verde"],
                            @[@"Cayman Islands"],
                            @[@"Central African Republic"],
                            @[@"Chad"],
                            @[@"Chile"],
                            @[@"China"],
                            @[@"Colombia"],
                            @[@"Comoros"],
                            @[@"Congo"],
                            @[@"Costa Rica"],
                            @[@"Croatia"],
                            @[@"Cuba"],
                            @[@"Cyprus"],
                            @[@"Czech Republic"],
                            // D
                            @[@"Democratic Republic of Congo"],
                            @[@"Denmark"],
                            @[@"Djibouti"],
                            @[@"Dominican Republic"],
                            @[@"Dominica"],
                            // E
                            @[@"Ecuador"],
                            @[@"Egypt"],
                            @[@"El Savador"],
                            @[@"Equitorial Guinea"],
                            @[@"Eritrea"],
                            @[@"Estonia"],
                            @[@"Ethiopia"],
                            // F
                            @[@"Fiji"],
                            @[@"Finland"],
                            @[@"France"],
                            // G
                            @[@"Gabon"],
                            @[@"Gambia"],
                            @[@"Georgia"],
                            @[@"Germany"],
                            @[@"Ghana"],
                            @[@"Greece"],
                            @[@"Grenada"],
                            @[@"Guatemala"],
                            @[@"Guinea"],
                            @[@"Guinea-Bissau"],
                            @[@"Guyana"],
                            // H
                            @[@"Haiti"],
                            @[@"Honduras"],
                            @[@"Hong Kong"],
                            @[@"Hungary"],
                            // I
                            @[@"Iceland"],
                            @[@"India"],
                            @[@"Indonesia"],
                            @[@"Iran"],
                            @[@"Iraq"],
                            @[@"Ireland"],
                            @[@"Israel"],
                            @[@"Italy"],
                            // J
                            @[@"Jamaica"],
                            @[@"Japan"],
                            @[@"Jordan"],
                            // K
                            @[@"Kazakhstan"],
                            @[@"Kenya"],
                            @[@"Kirbati"],
                            @[@"Kosovo"],
                            @[@"Kuwait"],
                            @[@"Kyrgzstan"],
                            // L
                            @[@"Laos"],
                            @[@"Latvia"],
                            @[@"Lebanon"],
                            @[@"Lesotho"],
                            @[@"Liberia"],
                            @[@"Libya"],
                            @[@"Liechenstein"],
                            @[@"Lithuania"],
                            @[@"Luxembourg"],
                            // M
                            @[@"Macao"],
                            @[@"Macedonia (FYROM)"],
                            @[@"Madagascar"],
                            @[@"Malawi"],
                            @[@"Malaysia"],
                            @[@"Maldives"],
                            @[@"Mali"],
                            @[@"Malta"],
                            @[@"Marshall Islands"],
                            @[@"Mauritius"],
                            @[@"Mexico"],
                            @[@"Micronesia"],
                            @[@"Moldova"],
                            @[@"Monaco"],
                            @[@"Mongolia"],
                            @[@"Montenegro"],
                            @[@"Morocco"],
                            @[@"Mozambique"],
                            // N
                            @[@"Namibia"],
                            @[@"Nauru"],
                            @[@"Nepal"],
                            @[@"Netherlands"],
                            @[@"New Zealand"],
                            @[@"Nicaragua"],
                            @[@"Niger"],
                            @[@"Nigeria"],
                            @[@"North Korea"],
                            @[@"Norway"],
                            // O
                            @[@"Oman"],
                            // P
                            @[@"Pakistan"],
                            @[@"Palau"],
                            @[@"Palestinian Territories"],
                            @[@"Panama"],
                            @[@"Papa New Guinea"],
                            @[@"Paraguay"],
                            @[@"Peru"],
                            @[@"Philippines"],
                            @[@"Poland"],
                            @[@"Portugal"],
                            // Q
                            @[@"Qatar"],
                            // R
                            @[@"Romania"],
                            @[@"Russian Federation"],
                            @[@"Rwanda"],
                            // S
                            @[@"Saint Kitts an Nevis"],
                            @[@"Saint Lucia"],
                            @[@"Samoa"],
                            @[@"San Marino"],
                            @[@"Sao Tome and Principe"],
                            @[@"Saudi Arabia"],
                            @[@"Senegal"],
                            @[@"Serbia"],
                            @[@"Seychelles"],
                            @[@"Sierra Leone"],
                            @[@"Singapore"],
                            @[@"Slovakia"],
                            @[@"Slovenia"],
                            @[@"Solomon Islands"],
                            @[@"Somalia"],
                            @[@"South Africa"],
                            @[@"South Korea"],
                            @[@"South Sudan"],
                            @[@"Spain"],
                            @[@"Sri Lanka"],
                            @[@"St. Vincent and the Grenadines"],
                            @[@"Sudan"],
                            @[@"Suriname"],
                            @[@"Swaziland"],
                            @[@"Sweeden"],
                            @[@"Switzerland"],
                            @[@"Syria"],
                            // T
                            @[@"Taiwan"],
                            @[@"Tajikistan"],
                            @[@"Tanzania"],
                            @[@"Thailand"],
                            @[@"Timor-Leste"],
                            @[@"Togo"],
                            @[@"Tonga"],
                            @[@"Trinidad and Tobago"],
                            @[@"Tunisia"],
                            @[@"Turkey"],
                            @[@"Turlmenistan"],
                            @[@"Tuvalu"],
                            // U
                            @[@"Uganda"],
                            @[@"Ukraine"],
                            @[@"UAE"],
                            @[@"United Kingdom"],
                            @[@"United States of America"],
                            @[@"Uruguay"],
                            @[@"Uzbekistan"],
                            // V
                            @[@"Vanuatu"],
                            @[@"Vatican City"],
                            @[@"Venezuela"],
                            @[@"Vietnam"],
                            // Y
                            @[@"Yemen"],
                            // Z
                            @[@"Zambia"],
                            @[@"Zimbabwe"]
                            
                            , nil]; */
        
        self.pickerArray = [NSArray arrayWithObjects:
                            
                            @[// A
                              @"Afghanistan",
                              @"Albania",
                              @"Algeria",
                              @"Andorra",
                              @"Angola",
                              @"Anguillia",
                              @"Antigua & Barbuda",
                              @"Argentina",
                              @"Armenia",
                              @"Australia",
                              @"Austria",
                              @"Azerbaijan",
                              // B
                              @"Bahamas",
                              @"Bahrain",
                              @"Bangladesh",
                              @"Barbados",
                              @"Belarus",
                              @"Belize",
                              @"Benin",
                              @"Bermuda",
                              @"Bhutan",
                              @"Bolivia",
                              @"Bosnia & Herzegovina",
                              @"Botzwana",
                              @"Brazil",
                              @"Brunei",
                              @"Bulgaria",
                              @"Burkina Faso",
                              @"Burma / Myanmar",
                              @"Burundi",
                              // C
                              @"Cambodia",
                              @"Cameroon",
                              @"Canada",
                              @"Cape Verde",
                              @"Cayman Islands",
                              @"Central African Republic",
                              @"Chad",
                              @"Chile",
                              @"China",
                              @"Colombia",
                              @"Comoros",
                              @"Congo",
                              @"Costa Rica",
                              @"Croatia",
                              @"Cuba",
                              @"Cyprus",
                              @"Czech Republic",
                              // D
                              @"Democratic Republic of Congo",
                              @"Denmark",
                              @"Djibouti",
                              @"Dominican Republic",
                              @"Dominica",
                              // E
                              @"Ecuador",
                              @"Egypt",
                              @"El Savador",
                              @"Equitorial Guinea",
                              @"Eritrea",
                              @"Estonia",
                              @"Ethiopia",
                              // F
                              @"Fiji",
                              @"Finland",
                              @"France",
                              // G
                              @"Gabon",
                              @"Gambia",
                              @"Georgia",
                              @"Germany",
                              @"Ghana",
                              @"Greece",
                              @"Grenada",
                              @"Guatemala",
                              @"Guinea",
                              @"Guinea-Bissau",
                              @"Guyana",
                              // H
                              @"Haiti",
                              @"Honduras",
                              @"Hong Kong",
                              @"Hungary",
                              // I
                              @"Iceland",
                              @"India",
                              @"Indonesia",
                              @"Iran",
                              @"Iraq",
                              @"Ireland",
                              @"Israel",
                              @"Italy",
                              // J
                              @"Jamaica",
                              @"Japan",
                              @"Jordan",
                              // K
                              @"Kazakhstan",
                              @"Kenya",
                              @"Kirbati",
                              @"Kosovo",
                              @"Kuwait",
                              @"Kyrgzstan",
                              // L
                              @"Laos",
                              @"Latvia",
                              @"Lebanon",
                              @"Lesotho",
                              @"Liberia",
                              @"Libya",
                              @"Liechenstein",
                              @"Lithuania",
                              @"Luxembourg",
                              // M
                              @"Macao",
                              @"Macedonia (FYROM)",
                              @"Madagascar",
                              @"Malawi",
                              @"Malaysia",
                              @"Maldives",
                              @"Mali",
                              @"Malta",
                              @"Marshall Islands",
                              @"Mauritius",
                              @"Mexico",
                              @"Micronesia",
                              @"Moldova",
                              @"Monaco",
                              @"Mongolia",
                              @"Montenegro",
                              @"Morocco",
                              @"Mozambique",
                              // N
                              @"Namibia",
                              @"Nauru",
                              @"Nepal",
                              @"Netherlands",
                              @"New Zealand",
                              @"Nicaragua",
                              @"Niger",
                              @"Nigeria",
                              @"North Korea",
                              @"Norway",
                              // O
                              @"Oman",
                              // P
                              @"Pakistan",
                              @"Palau",
                              @"Palestinian Territories",
                              @"Panama",
                              @"Papa New Guinea",
                              @"Paraguay",
                              @"Peru",
                              @"Philippines",
                              @"Poland",
                              @"Portugal",
                              // Q
                              @"Qatar",
                              // R
                              @"Romania",
                              @"Russian Federation",
                              @"Rwanda",
                              // S
                              @"Saint Kitts an Nevis",
                              @"Saint Lucia",
                              @"Samoa",
                              @"San Marino",
                              @"Sao Tome and Principe",
                              @"Saudi Arabia",
                              @"Senegal",
                              @"Serbia",
                              @"Seychelles",
                              @"Sierra Leone",
                              @"Singapore",
                              @"Slovakia",
                              @"Slovenia",
                              @"Solomon Islands",
                              @"Somalia",
                              @"South Africa",
                              @"South Korea",
                              @"South Sudan",
                              @"Spain",
                              @"Sri Lanka",
                              @"St. Vincent and the Grenadines",
                              @"Sudan",
                              @"Suriname",
                              @"Swaziland",
                              @"Sweeden",
                              @"Switzerland",
                              @"Syria",
                              // T
                              @"Taiwan",
                              @"Tajikistan",
                              @"Tanzania",
                              @"Thailand",
                              @"Timor-Leste",
                              @"Togo",
                              @"Tonga",
                              @"Trinidad and Tobago",
                              @"Tunisia",
                              @"Turkey",
                              @"Turlmenistan",
                              @"Tuvalu",
                              // U
                              @"Uganda",
                              @"Ukraine",
                              @"UAE",
                              @"United Kingdom",
                              @"United States of America",
                              @"Uruguay",
                              @"Uzbekistan",
                              // V
                              @"Vanuatu",
                              @"Vatican City",
                              @"Venezuela",
                              @"Vietnam",
                              // Y
                              @"Yemen",
                              // Z
                              @"Zambia",
                              @"Zimbabwe"
                              ], nil];
        
    }
    return self;
}

@end
